language: node_js

node_js:
  - 'node'
  - '10'

branches:
  only:
  - master
  - develop
  - /^release-.*/

install:
  - cd packages/example
  - yarn
  - yarn isomor:build
  - yarn serv:build
  - yarn build

cache:
  directories:
    - node_modules
