language: node_js

node_js:
  - 'node'

branches:
  only:
  - master
  - develop
  - /^release-.*/

install:
  - cp -r packages/isomor-transpiler ../isomor-transpiler # copy transpiler in isolated folder outside of lerna
  - cd packages/example
  - yarn

script:
  - yarn isomor:build
  - yarn serv:build
  - yarn build
  - yarn prod > /dev/null &
  - sleep 30
  - curl http://127.0.0.1:3005/
  - curl http://127.0.0.1:3005/isomor/status-server-getStatus/getStatus
  - cd ../../../isomor-transpiler
  - yarn
  - yarn test
  - pwd
  - cd ~ && mkdir npxisomorreactapp && cd npxisomorreactapp
  - npx isomor-react-app my-app
  - cd my-app
  - yarn isomor:build
  - yarn serv:build
  - yarn build

cache:
  directories:
    - node_modules
