language: node_js

node_js:
  - 'node'

branches:
  only:
  - master
  - develop
  - /^release-.*/

install:
  - cd packages/example
  - yarn

script:
  - yarn isomor:build
  - yarn serv:build
  - yarn build
  - yarn prod > /dev/null &
  - sleep 30
  - curl http://127.0.0.1:3005/
  - curl http://127.0.0.1:3005/isomor/status-server-getStatus/getStatus

cache:
  directories:
    - node_modules
