# https://pmarsceill.github.io/just-the-docs/docs/configuration/

remote_theme: pmarsceill/just-the-docs
search_enabled: true
#exclude:
#  - 'packages/isomor/Readme.md'

aux_links:
  "See on GitHub":
    - "//github.com/apiel/isomor"
