name: test on windows

on:
    repository_dispatch:
    push:
        branches:
            - master
    schedule:
        - cron: '0 4 * * *'

jobs:
    build:
        # runs-on: windows-latest
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Test isomor
              timeout-minutes: 20
              working-directory: ./test
              env:
                ISOMOR_HTTP_BASE_URL: http://127.0.0.1:3005
                COLUMNS: 80
                LINES: 40
              run: |
                  yarn add isomor @types/node cross-spawn
                  npx isomor-transpiler
                  node test.js
