name: test on windows

on:
    repository_dispatch:
    push:
        branches:
            - master
    schedule:
        - cron: '0 4 * * *'

jobs:
    build:
        # runs-on: windows-latest
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Test isomor
              timeout-minutes: 20
              working-directory: ./test
              run: |
                  yarn add isomor @types/node
                  npx isomor-transpiler
