name: test on windows

on:
    repository_dispatch:
    push:
        branches:
            - master
    schedule:
        - cron: '0 4 * * *'

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Test isomor
              timeout-minutes: 20
              run: |
                  cd test
                  yarn add isomor @types/node
                  npx isomor-transpiler
